### ISSUE TITLE
Replication clarifications

### ISSUE THREAD

**Issue by JensRantil** [dadgar/onecache#2]
The readme briefly states onecache supports replication. Is there a replication factor configurable somewhere? Is replication done on shutdown of a node? Is a node handed data on startup?

**Comment by dadgar** [comment]
Hey,

The replication factor is configurable. It is settable in the [config](https://github.com/dadgar/onecache/blob/master/onecache/config.go#L12) and via the cli with the [-replicas flag](https://github.com/dadgar/onecache/blob/master/main.go#L26)

Each node is responsible for a certain key space. All writes/reads are forwarded to the leader of a given key space. When a key is dirtied this causes a background replication to the configured number of replicas. When a node joins, leaders will replicate the data it should have to it.

**Comment by nikmahes** [comment]
Hi,
Even in case of increasing this value by either -replicas flag or in the config directly, only one peer is being created.
1) is this intentional ?
2) am I misunderstanding replicas with peers ?

Thanks !
